{
  "name": "quotes_demo",
  "base_url": "http://quotes.toscrape.com",
  "entrypoints": [
    {"url": "http://quotes.toscrape.com/page/1/"}
  ],
  "pagination": {"type": "next_link", "selector": "li.next a"},
  "items": {
    "Quote": {
      "match_url": "^/page/",
      "fields": {
        "url": {"from": "meta.url"},
        "text": {"candidates": [{"css": "span.text::text"}]},
        "author": {"candidates": [{"css": "small.author::text"}]},
        "tags": {"candidates": [{"css": ".tags a::text", "as": "list"}]}
      },
      "dedupe_keys": ["url", "text"]
    }
  },
  "pipelines": [
    {"type": "csv", "path": "out/quotes.csv"}
  ]
}
